org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
dg.testwithneu=true
signing.gnupg.keyName=28DC4ACD
loom.ignoreDependencyLoomVersionValidation=true
signing.gnupg.executable=/opt/homebrew/bin/gpg
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
org.gradle.console=plain
org.gradle.warning.mode=all
org.gradle.parallel=false
