pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven{ url "https://oss.sonatype.org/content/repositories/snapshots"}
        maven{ url "https://maven.architectury.dev/"}
        maven{ url "https://maven.fabricmc.net"}
        maven{ url "https://maven.minecraftforge.net/"}
        maven{ url "https://repo.spongepowered.org/maven/"}
        maven{ url "https://repo.essential.gg/repository/maven-public"}
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "gg.essential.loom") {
                useModule("gg.essential:architectury-loom:${requested.version}")
            }
        }
    }
}

plugins {
    id "gg.essential.loom" version "1.9+" apply false
    id "dev.architectury.architectury-pack200" version "0.1.3" apply false
}

include 'mod'
include '1.8.9-loader'
include 'modapi'

rootProject.name = "Dungeons Guide"

var versions = ["1.8.9", "1.21.6-fabric"]
for (final def ver in versions) {
    include(":"+ver)
    var p = project(":"+ver)
    p.projectDir = file("versions/${ver}")
}
gradle.beforeProject { project ->
    if (project.name.endsWith("fabric")) {
        project.ext.set("loom.platform", "fabric")
    } else {
        project.ext.set("loom.platform", "forge")
    }
}