package kr.syeyoung.modapi.world;

public enum BlockType {
    CHEST, AIR, SKULL, PRISMARINE, SEA_LANTERN, STONE_SLAB, IRON_BARS, END_PORTAL_FRAME, STONE_BUTTON, WOOD_PLANKS, BARRIER, STONE_BRICK, STONE, HARDENED_CLAY, STAINED_HARDENED_CLAY, DOUBLE_STONE_SLAB, CARPET, COAL_BLOCK, LEVER, SPONGE, FLOWING_WATER, STATIONARY_WATER, TRAP_CHEST,
    TAG_SLAB, BEDROCK, STANDING_SIGN, WALL_SIGN, QUARTZ_ORE, TAG_FENCE, TAG_WALL, TAG_STAIR
}
