package kr.syeyoung.modapi.item;

public enum Item {
    SKULL, DYE, UNKNOWN, MAP, FILLED_MAP, ARROW, STICK, GOLDEN_AXE, SPAWN_EGG, GOLDEN_SHOVEL, BEDROCK, BOOKSHELF, STAINED_GLASS_PANE, STAINED_HARDENED_CLAY;
}
