plugins {
    id "signing"
    id "idea"
    id "java"
    id "com.gradleup.shadow" version "8.3.6"
    id "gg.essential.loom"
}

version =  "4.0.0-beta13.0"
group = "kr.syeyoung.dungeonsguide"
archivesBaseName = "dungeonsguide"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
    sourceCompatibility = JavaLanguageVersion.of(21)
    targetCompatibility = JavaLanguageVersion.of(21)
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io/"
        content {
            includeGroupByRegex("(com|io)\\.github\\..+")
        }
    }
    maven { url "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
}

configurations {
    implementation.extendsFrom shadowImpl

    remappedMod {
        canBeConsumed = true
        canBeResolved = false
    }
    unmappedMod {
        canBeConsumed = true
        canBeResolved = false
    }
}

configurations {
    devenvMod {
        transitive = false
        visible = false
    }
}


dependencies {
    minecraft("com.mojang:minecraft:1.21.11")
    mappings("net.fabricmc:yarn:1.21.11+build.4")

    modImplementation("net.fabricmc:fabric-loader:0.18.4")
    modImplementation("net.fabricmc.fabric-api:fabric-api:0.141.2+1.21.11")

//    fabric
//    forge("net.minecraftforge:forge:1.8.9-11.15.1.2318-1.8.9")

    implementation "org.jetbrains:annotations-java5:19.0.0"

    compileOnly "org.projectlombok:lombok:1.18.36"
    annotationProcessor "org.projectlombok:lombok:1.18.36"

    testCompileOnly "org.projectlombok:lombok:1.18.36"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.36"

    shadowImpl project(path: ":modapi")
//    shadowImpl project(path: ":mod")

//    devenvMod(project(path: ":1.8.9-loader", configuration: "unmappedMod"))
    modLocalRuntime("me.djtheredstoner:DevAuth-fabric:1.2.2")
}


loom {
    accessWidenerPath = file("src/main/resources/dungeonsguide.accesswidener")
    mixin {
        useLegacyMixinAp.set(true)
        defaultRefmapName.set("mixins.dungeonsguide.refmap.json")
    }

    runs {
        client {
            ideConfigGenerated = true
            name = "Launch Dungeons Guide 1.21.11"
            runDir = '../../runtime/1.21.11'
            property('devauth.enabled', 'true')
            property('dg.loader', 'devenv')
            client()
//            vmArgs.remove("-XstartOnFirstThread")
        }
    }
}

afterEvaluate {
    loom.runs.named("client") {
        programArgs("--mods", configurations.devenvMod.files
                .collect { file("../../runtime/1.21.11").relativePath(it) }.join(","))
    }
}



tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

tasks.withType(Jar) {
    archivesBaseName = "dungeonsguide"
    manifest {}
}


tasks.shadowJar {
    archiveFileName = jar.archiveFileName

    configurations = [project.configurations.shadowImpl]

    enableRelocation = true
    relocationPrefix = "kr.syeyoung.dungeonsguide.libs"

    dependencies {
        exclude(dependency("org.json:json")) // provided via loader
    }
}

tasks.named("remapJar") {
    archiveClassifier = "mapped"
    dependsOn tasks.shadowJar
    inputFile = tasks.shadowJar.archiveFile
}



signing {
    required(project.findProperty("dg.dosign") == "true")
    useGpgCmd()
    sign tasks.remapJar, tasks.shadowJar
}

artifacts {
    remappedMod(tasks.remapJar)
    unmappedMod(tasks.shadowJar)
}


