plugins {
    id "signing"
    id "idea"
    id "java"
    id "com.gradleup.shadow" version "8.3.6"
}

version =  "4.0.0-beta13.0"
group = "kr.syeyoung.dungeonsguide"
archivesBaseName = "dungeonsguide"

java {
    sourceCompatibility = JavaLanguageVersion.of(8)
    targetCompatibility = JavaLanguageVersion.of(8)
}


sourceSets {
    main {
        java {
        }
    }
    java8 {
        java {
        }
    }
    java21 {
        java {
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io/"
        content {
            includeGroupByRegex("(com|io)\\.github\\..+")
        }
    }
    maven { url "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
    maven {
        url "https://libraries.minecraft.net"
    }
}

configurations {
    compileOnly.extendsFrom shadowImpl
}

configurations {
    mod {
        canBeConsumed = true
        canBeResolved = false
    }
}


def urlFile = { url, name ->
    File file = new File("$buildDir/download/${name}.jar")
    file.parentFile.mkdirs()
    if (!file.exists()) {
        new URL(url).withInputStream { downloadStream ->
            file.withOutputStream { fileOut ->
                fileOut << downloadStream
            }
        }
    }
    return file.absolutePath
}

def platform = net.fabricmc.loom.util.CurrentPlatform.INSTANCE

dependencies {
    implementation "org.jetbrains:annotations-java5:19.0.0"

//    shadowImpl 'net.java.dev.jna:jna:5.12.1' // sorry minecraft... i had to
    shadowImpl("org.java-websocket:Java-WebSocket:1.5.1") {
        exclude group: "org.json", module: "json"
    }

    shadowImpl "org.json:json:20240303"
    shadowImpl "javax.vecmath:vecmath:1.5.2"
    shadowImpl 'com.github.Dungeons-Guide:DiscordIPC:d403df89'
    shadowImpl "org.apache.commons:commons-compress:1.25.0"
    shadowImpl 'com.google.guava:guava:32.0.1-jre'


    shadowImpl('com.fasterxml.jackson.core:jackson-databind:2.18.2')
    shadowImpl 'com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.18.1'

    compileOnly "org.projectlombok:lombok:1.18.32"
    annotationProcessor "org.projectlombok:lombok:1.18.32"

    testCompileOnly "org.projectlombok:lombok:1.18.32"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.32"

    compileOnly 'org.apache.logging.log4j:log4j-core:2.25.3'

    compileOnly project(path: ":platform-api")
    compileOnly project(path: ":loader-api")
    shadowImpl project(path: ":auth-api")

    implementation("net.kyori:adventure-text-serializer-legacy:4.23.0")
}

ext.genOutputDir = file("$buildDir/generated-resources")
task generateVersionInfo {
    ext.outputFile = file("$genOutputDir/versionMeta.properties")
    outputs.file(outputFile)
    doLast {
        outputFile.text = "VERSION=${project.version}\nMANDATORY_VERSION=0"
    }
}
sourceSets.main.output.dir genOutputDir, builtBy: generateVersionInfo



tasks.named("compileJava8Java", JavaCompile) {
    source = sourceSets.java8.java
    classpath = sourceSets.java8.compileClasspath
    destinationDirectory = file("$buildDir/classes/java/java8")
    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
    sourceCompatibility =  JavaLanguageVersion.of(8)
    targetCompatibility =  JavaLanguageVersion.of(8)
}

tasks.named("compileJava", JavaCompile) {
    classpath += sourceSets.java8.output
    destinationDirectory = file("$buildDir/classes/java/main")

    dependsOn tasks.compileJava8Java

    sourceCompatibility =  JavaLanguageVersion.of(8)
    targetCompatibility =  JavaLanguageVersion.of(8)
}
tasks.named("compileJava21Java", JavaCompile) {
    source = sourceSets.java21.java
    classpath = sourceSets.java21.compileClasspath
    destinationDirectory = file("$buildDir/classes/java/java21")
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.compilerArgs += ["-parameters"]
}

tasks.withType(Jar) {
    archivesBaseName = "dungeonsguide"
    manifest { attributes 'Multi-Release': 'true' }

    // Default classes (Java 8 common + impl)
    from("$buildDir/classes/java/main")
    from("$buildDir/classes/java/java8")

    // Java 21 version in META-INF/versions/21
    from("$buildDir/classes/java/java21") {
        into 'META-INF/versions/21'
    }

    dependsOn tasks.java8Classes, tasks.java21Classes, tasks.classes
}


tasks.shadowJar {
    archiveFileName = jar.archiveFileName

    configurations = [project.configurations.shadowImpl]

    manifest { attributes 'Multi-Release': 'true' }

    // Default classes (Java 8 common + impl)
    from("$buildDir/classes/java/common")
    from("$buildDir/classes/java/java8")

    // Java 21 version in META-INF/versions/21
    from("$buildDir/classes/java/java21") {
        into 'META-INF/versions/21'
    }


    enableRelocation = true
    relocationPrefix = "kr.syeyoung.dungeonsguide.mod.libs"

//    dependencies {
////        exclude(dependency("org.json:json")) // provided via loader
//    }

    dependsOn tasks.classes, tasks.java8Classes, tasks.java21Classes

}

tasks.build {
    dependsOn tasks.shadowJar
}

signing {
    required(project.findProperty("dg.dosign") == "true")
    useGpgCmd()
    sign tasks.shadowJar
}

artifacts {
    mod tasks.shadowJar
}