plugins {
    id "signing"
    id "idea"
    id "java"
    id "com.gradleup.shadow" version "8.3.6"
    id "dev.architectury.architectury-pack200"
    id "gg.essential.loom"
}

version =  "4.0.0-beta13.0"
group = "kr.syeyoung.dungeonsguide"
archivesBaseName = "dungeonsguide"

java {
    sourceCompatibility = JavaLanguageVersion.of(8)
    targetCompatibility = JavaLanguageVersion.of(8)
}


sourceSets {
    main {
        java {
            exclude("**/dungeon/roomedit/**")
        }
    }
    java8 {
        java {
        }
    }
    java21 {
        java {
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io/"
        content {
            includeGroupByRegex("(com|io)\\.github\\..+")
        }
    }
    maven { url "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
}

configurations {
    implementation.extendsFrom shadowImpl
    
    remappedMod {
        canBeConsumed = true
        canBeResolved = false
    }
    unmappedMod {
        canBeConsumed = true
        canBeResolved = false
    }
}

configurations {
    devenvMod {
        transitive = false
        visible = false
    }
}


def urlFile = { url, name ->
    File file = new File("$buildDir/download/${name}.jar")
    file.parentFile.mkdirs()
    if (!file.exists()) {
        new URL(url).withInputStream { downloadStream ->
            file.withOutputStream { fileOut ->
                fileOut << downloadStream
            }
        }
    }
    return file.absolutePath
}

def platform = net.fabricmc.loom.util.CurrentPlatform.INSTANCE

dependencies {
    minecraft("com.mojang:minecraft:1.8.9")
    mappings("de.oceanlabs.mcp:mcp_stable:22-1.8.9")
    forge("net.minecraftforge:forge:1.8.9-11.15.1.2318-1.8.9")

    def os = platform.getOperatingSystem();
    if (platform.getArchitecture().isArm()) {
        if (os.isLinux() && platform.getArchitecture().is64Bit()) {
            minecraftNatives(files(urlFile("https://github.com/theofficialgman/lwjgl3-binaries-arm64/raw/lwjgl-2.9.4/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar", "lwjgl-platform-2.9.4-nightly-20150209-natives-linux-arm64.jar"),
                    urlFile("https://github.com/theofficialgman/lwjgl3-binaries-arm64/raw/lwjgl-2.9.4/jinput-platform-2.0.5-natives-linux.jar", "jinput-platform-2.0.5-natives-linux-arm64.jar")))
        } else if (os.isLinux() && !platform.getArchitecture().is64Bit()) {
            minecraftNatives(files(urlFile("https://github.com/theofficialgman/lwjgl3-binaries-arm32/raw/lwjgl-2.9.4/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar", "lwjgl-platform-2.9.4-nightly-20150209-natives-linux-arm32.jar"),
                    urlFile("https://github.com/theofficialgman/lwjgl3-binaries-arm32/raw/lwjgl-2.9.4/jinput-platform-2.0.5-natives-linux.jar", "jinput-platform-2.0.5-natives-linux-arm32.jar")))
        } else if (os.isMacOS()) {
            minecraftNatives(files(urlFile("https://github.com/Dungeons-Guide/lwjgl/releases/download/2.9.4-20150209-mmachina.2-syeyoung.1/lwjgl-platform-2.9.4-nightly-20150209-natives-osx-arm64.jar", "lwjgl-platform-2.9.4-nightly-20150209-natives-osx-arm64.jar"),
                    urlFile("https://github.com/r58Playz/jinput-m1/raw/main/plugins/OSX/bin/jinput-platform-2.0.5.jar", "jinput-platform-2.0.5-natives-osx-arm64.jar")))
        }
    }

    implementation "org.jetbrains:annotations-java5:19.0.0"

//    shadowImpl "org.json:json:20240303"
//    shadowImpl 'net.java.dev.jna:jna:5.12.1' // sorry minecraft... i had to
    shadowImpl("org.java-websocket:Java-WebSocket:1.5.1") {
        exclude group: "org.json", module: "json"
    }
    shadowImpl 'com.github.Dungeons-Guide:DiscordIPC:d403df89'
    shadowImpl "com.twelvemonkeys.imageio:imageio-bmp:3.7.0"
    shadowImpl('com.fasterxml.jackson.core:jackson-databind:2.18.2')
    shadowImpl 'com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.18.1'

    compileOnly "org.projectlombok:lombok:1.18.32"
    annotationProcessor "org.projectlombok:lombok:1.18.32"

    testCompileOnly "org.projectlombok:lombok:1.18.32"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.32"

    compileOnly project(path: ":modapi")
    compileOnly project(path: ":1.8.9-loader")

    implementation("net.kyori:adventure-text-serializer-legacy:4.23.0")
}


loom {
    if (platform.getArchitecture().isArm()) {
        loom.customMinecraftManifest = "https://gist.githubusercontent.com/cyoung06/76a8208bd4575c17bdb138a0771c0886/raw/beb9ef6cc3c26abf5014d810133d21bedbffa9bb/1.8.9.json"
    }
    runs {
    }
    forge {
        pack200Provider.set(new dev.architectury.pack200.java.Pack200Adapter())
    }
}


tasks.named("compileJava8Java", JavaCompile) {
    source = sourceSets.java8.java
    classpath = sourceSets.java8.compileClasspath
    destinationDirectory = file("$buildDir/classes/java/java8")
    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
    sourceCompatibility =  JavaLanguageVersion.of(8)
    targetCompatibility =  JavaLanguageVersion.of(8)
}

tasks.named("compileJava", JavaCompile) {
    classpath += sourceSets.java8.output
    destinationDirectory = file("$buildDir/classes/java/main")

    dependsOn tasks.compileJava8Java

    sourceCompatibility =  JavaLanguageVersion.of(8)
    targetCompatibility =  JavaLanguageVersion.of(8)
}
tasks.named("compileJava21Java", JavaCompile) {
    source = sourceSets.java21.java
    classpath = sourceSets.java21.compileClasspath
    destinationDirectory = file("$buildDir/classes/java/java21")
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

tasks.withType(Jar) {
    archivesBaseName = "dungeonsguide"
    manifest { attributes 'Multi-Release': 'true' }

    // Default classes (Java 8 common + impl)
    from("$buildDir/classes/java/main")
    from("$buildDir/classes/java/java8")

    // Java 21 version in META-INF/versions/21
    from("$buildDir/classes/java/java21") {
        into 'META-INF/versions/21'
    }

    dependsOn tasks.java8Classes, tasks.java21Classes, tasks.classes
}


tasks.shadowJar {
    archiveFileName = jar.archiveFileName

    configurations = [project.configurations.shadowImpl]

    manifest { attributes 'Multi-Release': 'true' }

    // Default classes (Java 8 common + impl)
    from("$buildDir/classes/java/common")
    from("$buildDir/classes/java/java8")

    // Java 21 version in META-INF/versions/21
    from("$buildDir/classes/java/java21") {
        into 'META-INF/versions/21'
    }


    enableRelocation = true
    relocationPrefix = "kr.syeyoung.dungeonsguide.libs"

    dependencies {
        exclude(dependency("org.json:json")) // provided via loader
    }

    dependsOn tasks.classes, tasks.java8Classes, tasks.java21Classes

}

tasks.named("remapJar") {
    archiveClassifier = "mapped"
    dependsOn tasks.shadowJar
    inputFile = tasks.shadowJar.archiveFile
}



signing {
    required(project.findProperty("dg.dosign") == "true")
    useGpgCmd()
    sign tasks.remapJar, tasks.shadowJar
}

artifacts {
    remappedMod(tasks.remapJar)
    unmappedMod(tasks.shadowJar)
}


