package kr.syeyoung.modapi.entity;

public enum EntityType {
    PLAYER, BAT, ITEM, ENDER_CRYSTAL, SKELETON, WITHER, GUARDIAN, IRON_GOLEM, GIANT, SHEEP, COW, CHICKEN, WOLF, RABBIT, GHAST, FALLING_BLOCK, ARMOR_STAND, ITEM_FRAME,BLAZE, UNKNOWN
}
